---
- name: "apache installation"
  hosts: prod
  become: true
  vars_files:
    - files/secretes/credentials.yml
  pre_tasks:
  - name: Install some packages 
    package: name='{{ item }}' state=present
    when: ansible_distribution == "CentOS"
    loop:
      - epel-release
      - git
      - wget
  - name: download pip script
    get_url:
     url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
     dest: /tmp/get-pip.py
  - name: install python-pip
    command: python2.7 /tmp/get-pip.py
  - name: Install docker pyton
    pip: name=docker-py

  tasks:
    - name: copy website
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: Create Apache container
      become: yes
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/webapp-ansible-apache/.:/home/test/
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
